config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :recipes
  
  get '/about', to: 'home#about', as: 'about'
 
  get 'admin/index'

  get '/admin', to: 'admin#index', as: 'index'
  
  root to: 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes, :dependent => :nullify
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category
  validates :title, uniqueness: true
  validates_presence_of :title, :ingredients, :instructions, :calories

  def self.find_all_by_query(query)
    query = query.downcase
    query = "%#{query}%"

    Recipe.where(['lower(title) like ?
                  OR lower(ingredients) like ?
                  OR lower(instructions) like ?',
                  query, query, query])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  def self.authenticate(username, password)
    user = User.where(username: username).first
    user && user.authenticate(password)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate
  
  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :setTitle

  helper_method :logged_in?
  helper_method :current_user

  
  def setTitle
    @title = 'Cookbook'
  end
  
  protect_from_forgery with: :exception

  def logged_in?
    session[:logged_in]
  end

  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      session[:logged_in] = (user_name == 'admin' && password == 'password')
    end
  end

  def authenticate
    if user = authenticate_with_http_basic {|user, password| User.authenticate(user, password)}
      session[:user_id] = user.id
      session[:logged_in] = true
    else
      request_http_basic_authentication
    end
  end
  
    def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @number_of_recipes = Recipe.count
    @latest_recipe = Recipe.last
  end

  def about
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate, :except => [:index, :show]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, :only =>[:new, :edit, :create, :update]

  # GET /recipes
  # GET /recipes.json
  def index
    if params[:q]
      @recipes = Recipe.find_all_by_query(params[:q])
    else
      @recipes = Recipe.all
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @title = 'Recipe Details'
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @title = 'New Recipe'
    @categories = Category.all.collect{|c| [c.name, c.id] }
  end

  # GET /recipes/1/edit
  def edit
    @title = 'Edit Recipe'
    @categories = Category.all.collect{|c| [c.name, c.id] }
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.includes(:category).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :ingredients, :instructions, :calories, :category_id)
    end

    def get_categories
      @categories = Category.all.collect{|c| [c.name, c.id]}
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password_digest)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<% if logged_in? %>
    <p>You are logged in as <%= current_user.username %></p>
<% end %>

app/views/home/about.html.erb
￼<h2>About</h2>
<p>This is a simple cookbook application I wrote. I hope you like it.</p>

app/views/home/index.html.erb
<%= render "/shared/search" %>

<h2>Latest Recipes</h2>
<p>There are <%= @number_of_recipes %> recipes total.</p>

<h3>Latest Recipes</h3>

<% if @latest_recipe %>

  <div class="inset">
    <h4><%=@latest_recipe.title %></h4>
    <p><%=@latest_recipe.ingredients %></p>
    <p><%=@latest_recipe.instructions %></p>
  </div>

<% else %>

  <p>Sorry! No recipes to display.</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title><%= @title %></title>
    <%= stylesheet_link_tag    'application',
      media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <header>
        <h1>Our Cookbook</h1>
      </header>
      <nav>
        <%=link_to_unless_current 'Home', root_url %>
        <%=link_to_unless_current 'Recipes', recipes_url %>
        <%=link_to_unless_current 'About', about_url %>
      </nav>
      <% if notice %>
      <div id="notice">
        <%= notice %>
      </div>
      <% end %>
      <section class="content">
        <%= yield %>
      </section>
      <footer>
        <h4>Copyright <%=Date.today.year %> OurCookbook</h4>
      </footer>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h5><u>Note: fields with * are required.</u></h5>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %> *
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %> *
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %> *
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.text_area :calories %> *
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%= render "/shared/search" %>

<h1>Listing recipes</h1>
<table> <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Last Updated</th>
    <th colspan="2">&nbsp;</th>
</tr>
  <% @recipes.each do |recipe| %>
  <tr>
    <td><%= link_to recipe.title, recipe %></td>
    <td><%= recipe.category.name rescue "No category" %></td>
    <td><%= time_ago_in_words(recipe.updated_at) %> ago</td>
    <td><% if logged_in? %>
      <%= link_to 'Edit', edit_recipe_path(recipe) %>
    <% end %></td>
    <td><% if logged_in? %>
      <%= button_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete
 %>
    <% end %></td>
  </tr>
  <% end %>
</table>
<% if logged_in? %>
  <%= link_to 'New Recipe', new_recipe_path %>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<article>
  <header>
    <h2>
      <%= @recipe.title %>
      [ <%= link_to 'Edit', edit_recipe_path(@recipe) %> ]
     </h2>
  </header>
  <h3>Category:</h3>
  <p><%= h(@recipe.category.name) rescue 'No category found' %></p>
  <h3>Ingredients:</h3>
  <p><%= @recipe.ingredients %></p>
  <h3>Instructions</h3>
  <p><%= @recipe.instructions %></p>
  <h3>Calories</h3>
  <p><%= @recipe.calories %></p>
</article>
<p><%= link_to 'Back', recipes_path %></p>

app/views/shared/_search.html.erb
<%= form_tag recipes_url, method: :get do %>
  <label for="query">Keywords: </label>
  <input type="search" id="query" name="q" value="<%= params[:q] %>">
  <input type="submit" value="Search">
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>